### ISSUE TITLE
initial step matching is done with non-augmented predicates when show_all_missing=True

### ISSUE THREAD

**Issue by anentropic** [kidosoft/Morelia#123]
* Morelia version: 0.7.1
* Python version: 2.7

### Description

`show_all_missing=True` does an initial matching pass where the `augmented_predicate` is not augmented yet

this prevents using a regex like `(\d+)` to match steps which have numeric variable substitutions because the regex needs to match `<variable_name>` instead

if I set `show_all_missing=False` then I can regex match on augmented predicates like I wanted

**Comment by dryobates** [comment]
@anentropic Fixed in versions 0.7.2 and 0.9.2.

**Comment by anentropic** [comment]
great!

is `0.7.2` a backport of this fix on top of the Python 2.7-compatible version `0.7.1`?

we currently have a fork fixing an issue when running Morelia tests under `coverage.py... if you're open to adding further minor bugfixes to the `py27` branch I'll open a PR for that

P.S. please publish a `0.7.2` git tag

**Comment by dryobates** [comment]
@anentropic Jest 0.7.2 is a backport on top of 0.7.1. I've just published missing tags.

Any bug fixes are always welcome :) I'll be glad to merge them.
